### ISSUE TITLE
我之前写过类似东西

### ISSUE THREAD

**Issue by GaryChangCN** [Seasonley/ishouit#1]
https://github.com/GaryChangCN/ShouMedia
http://www.shouedu.cn
现在正要重写 新技术栈 vue+vuex+nodejs+koajs+mongodb+（weex/cordova+electron）
是准备覆盖桌面端+移动端+浏览器端的
数据不从i海大爬了  准备直接官网爬  i海大课程表不对 
有没有兴趣一起来

**Comment by Seasonley** [comment]
不过我是angular派的，i海大指不定哪天挂了，官网爬可以。我平时时间不多，已经毕业工作了。

**Comment by GaryChangCN** [comment]
我权衡了angular1.5和vue 最后决定是vue。这个东西是我大创申请的，--! 现在我也不怎么想写了，没办法。

**Comment by ttorange** [comment]
教务系统更新了，课程表和成绩都查不了了

**Comment by GaryChangCN** [comment]
@ttorange 我现在没有权限来看教务系统了，既然更新了说不定现在用前端渲染了，那接口就不用解析了。
